#!/usr/bin/env node
'use strict';

/**
 * build-gallery.js
 *
 * Recursively scans assets/pictures/<Category>/ and all sub-folders,
 * then writes assets/js/gallery-data.js (window.GALLERY_DATA).
 *
 * Usage:
 *   node scripts/build-gallery.js          (or: npm run build:gallery)
 *
 * To add new photos: drop them anywhere inside assets/pictures/<Category>/
 * (any depth) and re-run.  No HTML changes needed.
 *
 * To add a new service category:
 *   1. Create assets/pictures/<NewFolder>/
 *   2. Add an entry to CATEGORY_META below.
 *   3. Re-run this script.
 */

const fs   = require('fs');
const path = require('path');

// ── Configuration ─────────────────────────────────────────────────────────────

const PROJECT_ROOT = path.join(__dirname, '..');
const PICTURES_DIR = path.join(PROJECT_ROOT, 'assets', 'pictures');
const OUTPUT_FILE  = path.join(PROJECT_ROOT, 'assets', 'js', 'gallery-data.js');

/**
 * Category folders to include.
 * Folders NOT listed here are silently ignored (keeps test/draft images off the site).
 *   key — lowercase key used in data-gallery-category attributes
 *   alt — base alt-text prefix for every image in the category
 */
const CATEGORY_META = {
  Bathroom:    { key: 'bathroom',    alt: 'Bathroom renovation'   },
  Kitchen:     { key: 'kitchen',     alt: 'Kitchen renovation'    },
  Flooring:    { key: 'flooring',    alt: 'Flooring installation' },
  Painting:    { key: 'painting',    alt: 'House painting'        },
  Tiling:      { key: 'tiling',      alt: 'Tiling installation'   },
  Landscaping: { key: 'landscaping', alt: 'Landscaping project'   },
};

const VALID_EXT = new Set(['.jpg', '.jpeg', '.png', '.webp', '.avif', '.gif']);

// ── Helpers ───────────────────────────────────────────────────────────────────

/**
 * Recursively walk `dir` and return every image file found at any depth,
 * as paths relative to PROJECT_ROOT using forward slashes.
 */
function collectImages(dir) {
  if (!fs.existsSync(dir)) return [];
  const results = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...collectImages(full));
    } else if (VALID_EXT.has(path.extname(entry.name).toLowerCase())) {
      // Store as a forward-slash path relative to the project root
      results.push(path.relative(PROJECT_ROOT, full).replace(/\\/g, '/'));
    }
  }
  return results.sort();
}

// ── Main ──────────────────────────────────────────────────────────────────────

if (!fs.existsSync(PICTURES_DIR)) {
  console.error(`ERROR: Pictures directory not found: ${PICTURES_DIR}`);
  process.exit(1);
}

const data = {};
let totalImages = 0;

for (const [folder, meta] of Object.entries(CATEGORY_META)) {
  const folderPath = path.join(PICTURES_DIR, folder);

  if (!fs.existsSync(folderPath) || !fs.statSync(folderPath).isDirectory()) {
    console.warn(`  WARN: Folder not found, skipping: ${folder}`);
    continue;
  }

  const files = collectImages(folderPath);

  if (files.length === 0) {
    console.warn(`  WARN: No images found in ${folder}/, skipping.`);
    continue;
  }

  data[meta.key] = files.map((src, i) => ({
    src,
    alt:      `${meta.alt} project ${i + 1}`,
    category: meta.key,
  }));

  totalImages += files.length;
  console.log(`  ${folder}: ${files.length} image(s)`);
}

// ── Write output ──────────────────────────────────────────────────────────────

const output = [
  '// AUTO-GENERATED by scripts/build-gallery.js — do not edit by hand.',
  '// Run `npm run build:gallery` locally or push to Netlify to regenerate.',
  '// Drop images anywhere inside assets/pictures/<Category>/ and re-run.',
  `window.GALLERY_DATA = ${JSON.stringify(data, null, 2)};`,
  '',
].join('\n');

fs.writeFileSync(OUTPUT_FILE, output, 'utf8');

console.log(`\n✓ gallery-data.js written — ${totalImages} images across ${Object.keys(data).length} categories.`);
