#!/usr/bin/env node
'use strict';

/**
 * build-gallery.js
 *
 * Scans assets/pictures/<Category>/ subdirectories and generates
 * assets/js/gallery-data.js — a tiny JS file that sets window.GALLERY_DATA.
 *
 * Usage:
 *   node scripts/build-gallery.js
 *
 * Run this whenever you add or remove pictures from any category folder.
 * On Netlify this runs automatically as part of the build command.
 *
 * To add a new category:
 *   1. Create a new subfolder under assets/pictures/  (e.g. assets/pictures/Decking/)
 *   2. Add an entry to CATEGORY_META below with its display label and alt text.
 *   3. Run this script (or push to Netlify) — no HTML changes needed.
 */

const fs   = require('fs');
const path = require('path');

// ── Configuration ────────────────────────────────────────────────────────────

const PICTURES_DIR = path.join(__dirname, '..', 'assets', 'pictures');
const OUTPUT_FILE  = path.join(__dirname, '..', 'assets', 'js', 'gallery-data.js');

/**
 * Map each folder name to:
 *   key  — the lowercase filter key used by the JS filter buttons (data-filter)
 *   alt  — base alt text for every image in that category
 *
 * Folders not listed here are silently ignored, so you can keep test/draft
 * folders without them appearing on the site.
 */
const CATEGORY_META = {
  Bathroom:    { key: 'bathroom',    alt: 'Bathroom renovation'    },
  Kitchen:     { key: 'kitchen',     alt: 'Kitchen renovation'     },
  Flooring:    { key: 'flooring',    alt: 'Flooring installation'  },
  Painting:    { key: 'painting',    alt: 'House painting'         },
  Tiling:      { key: 'tiling',      alt: 'Tiling installation'    },
  Landscaping: { key: 'landscaping', alt: 'Landscaping project'    },
};

const VALID_EXTENSIONS = new Set(['.jpg', '.jpeg', '.png', '.webp', '.avif', '.gif']);

// ── Scan folders ─────────────────────────────────────────────────────────────

if (!fs.existsSync(PICTURES_DIR)) {
  console.error(`ERROR: Pictures directory not found: ${PICTURES_DIR}`);
  process.exit(1);
}

const data = {};
let totalImages = 0;

for (const [folder, meta] of Object.entries(CATEGORY_META)) {
  const folderPath = path.join(PICTURES_DIR, folder);

  if (!fs.existsSync(folderPath) || !fs.statSync(folderPath).isDirectory()) {
    console.warn(`  WARN: Folder not found, skipping: ${folder}`);
    continue;
  }

  const images = fs
    .readdirSync(folderPath)
    .filter(f => VALID_EXTENSIONS.has(path.extname(f).toLowerCase()))
    .sort()
    .map((filename, index) => ({
      src: `assets/pictures/${folder}/${filename}`,
      alt: `${meta.alt} project ${index + 1}`,
      category: meta.key,
    }));

  if (images.length > 0) {
    data[meta.key] = images;
    totalImages += images.length;
    console.log(`  ${folder}: ${images.length} image(s)`);
  } else {
    console.warn(`  WARN: No images found in ${folder}, skipping.`);
  }
}

// ── Write output ─────────────────────────────────────────────────────────────

const output = [
  '// AUTO-GENERATED by scripts/build-gallery.js — do not edit by hand.',
  '// Run `npm run build:gallery` locally or push to Netlify to regenerate.',
  '// Add images to assets/pictures/<Category>/ and re-run to update the gallery.',
  `window.GALLERY_DATA = ${JSON.stringify(data, null, 2)};`,
  '',
].join('\n');

fs.writeFileSync(OUTPUT_FILE, output, 'utf8');

console.log(`\n✓ gallery-data.js written with ${totalImages} images across ${Object.keys(data).length} categories.`);
console.log(`  → ${OUTPUT_FILE}`);
